{ config, pkgs, lib, ... }:

{
   services.zapret.enable = true;
   services.zapret.whitelist = [ "discord.com" "cdn.discordapp.com" "media.discordapp.net" "discordapp.com" "gateway.discord.gg" "discord.gg" "status.discord.com" "apis.discord.com" "discordapp.net" "roblox.com" ];
   services.zapret.params = [
     "--hostspell=hoSt"
     "--dpi-desync=fake --dpi-desync-ttl=3"
     "--dpi-desync=fake --dpi-desync-fooling=md5sig"
     "--dpi-desync=fakedsplit --dpi-desync-ttl=3 --dpi-desync-split-pos=method+2"
     "--dpi-desync=fakedsplit --dpi-desync-fooling=badsum --dpi-desync-split-pos=method+2"
     "--dpi-desync=fakedsplit --dpi-desync-fooling=md5sig --dpi-desync-split-pos=method+2"
     "--dpi-desync=fakeddisorder --dpi-desync-ttl=3 --dpi-desync-split-pos=method+2"
     "--dpi-desync=fakeddisorder --dpi-desync-fooling=badsum --dpi-desync-split-pos=method+2"
     "--dpi-desync=fakeddisorder --dpi-desync-fooling=md5sig --dpi-desync-split-pos=method+2"
     "--dpi-desync=multidisorder --dpi-desync-split-pos=method+2 --dpi-desync-split-seqovl=method+1"
     "--dpi-desync=multidisorder --dpi-desync-split-pos=midsld --dpi-desync-split-seqovl=midsld-1"
     "--dpi-desync=multidisorder --dpi-desync-split-pos=method+2,midsld --dpi-desync-split-seqovl=method+1"
     "--dpi-desync=fake --dpi-desync-ttl=1 --dpi-desync-autottl=1"
     "--dpi-desync=fake --dpi-desync-ttl=1 --dpi-desync-autottl=2"
     "--dpi-desync=fake --dpi-desync-ttl=1 --dpi-desync-autottl=3"
     "--dpi-desync=fake --dpi-desync-ttl=1 --dpi-desync-autottl=4"
     "--dpi-desync=fake --dpi-desync-ttl=1 --dpi-desync-autottl=5"
     "--dpi-desync=fakedsplit --dpi-desync-ttl=1 --dpi-desync-autottl=1 --dpi-desync-split-pos=method+2"
     "--dpi-desync=fakedsplit --dpi-desync-ttl=1 --dpi-desync-autottl=2 --dpi-desync-split-pos=method+2"
     "--dpi-desync=fakedsplit --dpi-desync-ttl=1 --dpi-desync-autottl=3 --dpi-desync-split-pos=method+2"
     "--dpi-desync=fakedsplit --dpi-desync-ttl=1 --dpi-desync-autottl=4 --dpi-desync-split-pos=method+2"
     "--dpi-desync=fakedsplit --dpi-desync-ttl=1 --dpi-desync-autottl=5 --dpi-desync-split-pos=method+2"
     "--dpi-desync=fakeddisorder --dpi-desync-ttl=1 --dpi-desync-autottl=1 --dpi-desync-split-pos=method+2"
     "--dpi-desync=fakeddisorder --dpi-desync-ttl=1 --dpi-desync-autottl=2 --dpi-desync-split-pos=method+2"
     "--dpi-desync=fakeddisorder --dpi-desync-ttl=1 --dpi-desync-autottl=3 --dpi-desync-split-pos=method+2"
     "--dpi-desync=fakeddisorder --dpi-desync-ttl=1 --dpi-desync-autottl=4 --dpi-desync-split-pos=method+2"
     "--dpi-desync=fakeddisorder --dpi-desync-ttl=1 --dpi-desync-autottl=5 --dpi-desync-split-pos=method+2"
     "--dpi-desync=fake --dpi-desync-ttl=3"
     "--dpi-desync=fake --dpi-desync-fooling=md5sig"
     "--dpi-desync=fakedsplit --dpi-desync-ttl=3 --dpi-desync-split-pos=1"
     "--dpi-desync=fakedsplit --dpi-desync-fooling=badsum --dpi-desync-split-pos=1"
     "--dpi-desync=fakedsplit --dpi-desync-fooling=md5sig --dpi-desync-split-pos=1"
     "--dpi-desync=fakeddisorder --dpi-desync-ttl=3 --dpi-desync-split-pos=1"
     "--dpi-desync=fakeddisorder --dpi-desync-fooling=badsum --dpi-desync-split-pos=1"
     "--dpi-desync=fakeddisorder --dpi-desync-fooling=md5sig --dpi-desync-split-pos=1"
     "--dpi-desync=multidisorder --dpi-desync-split-pos=2 --dpi-desync-split-seqovl=1"
     "--dpi-desync=multidisorder --dpi-desync-split-pos=sniext+1 --dpi-desync-split-seqovl=sniext"
     "--dpi-desync=multidisorder --dpi-desync-split-pos=sniext+4 --dpi-desync-split-seqovl=sniext+3"
     "--dpi-desync=multidisorder --dpi-desync-split-pos=midsld --dpi-desync-split-seqovl=midsld-1"
     "--dpi-desync=multidisorder --dpi-desync-split-pos=2,midsld --dpi-desync-split-seqovl=1"
     "--dpi-desync=fake --dpi-desync-ttl=1 --dpi-desync-autottl=1"
     "--dpi-desync=fake --dpi-desync-ttl=1 --dpi-desync-autottl=2"
     "--dpi-desync=fake --dpi-desync-ttl=1 --dpi-desync-autottl=3"
     "--dpi-desync=fake --dpi-desync-ttl=1 --dpi-desync-autottl=4"
     "--dpi-desync=fake --dpi-desync-ttl=1 --dpi-desync-autottl=5"
     "--dpi-desync=fakedsplit --dpi-desync-ttl=1 --dpi-desync-autottl=1 --dpi-desync-split-pos=1"
     "--dpi-desync=fakedsplit --dpi-desync-ttl=1 --dpi-desync-autottl=2 --dpi-desync-split-pos=1"
     "--dpi-desync=fakedsplit --dpi-desync-ttl=1 --dpi-desync-autottl=3 --dpi-desync-split-pos=1"
     "--dpi-desync=fakedsplit --dpi-desync-ttl=1 --dpi-desync-autottl=4 --dpi-desync-split-pos=1"
     "--dpi-desync=fakedsplit --dpi-desync-ttl=1 --dpi-desync-autottl=5 --dpi-desync-split-pos=1"
     "--dpi-desync=fakeddisorder --dpi-desync-ttl=1 --dpi-desync-autottl=1 --dpi-desync-split-pos=1"
     "--dpi-desync=fakeddisorder --dpi-desync-ttl=1 --dpi-desync-autottl=2 --dpi-desync-split-pos=1"
     "--dpi-desync=fakeddisorder --dpi-desync-ttl=1 --dpi-desync-autottl=3 --dpi-desync-split-pos=1"
     "--dpi-desync=fakeddisorder --dpi-desync-ttl=1 --dpi-desync-autottl=4 --dpi-desync-split-pos=1"
     "--dpi-desync=fakeddisorder --dpi-desync-ttl=1 --dpi-desync-autottl=5 --dpi-desync-split-pos=1"
  ];
}
