{ config, pkgs, lib, ... }:

{
  environment.systemPackages = with pkgs; [
    vim
    wget
    curl
    git
    htop
    fastfetch
    firefox-bin
    hyprland
    waybar
    rofi-wayland
    kdePackages.dolphin
    kdePackages.konsole
    hyprpaper
    kdePackages.kdeconnect-kde
    wl-clipboard
    cliphist
    easyeffects
    kdePackages.polkit-kde-agent-1
    qt6.qtwayland
    kdePackages.kirigami
    qt6.qtdeclarative
    mako
    hypridle
    steam
    networkmanagerapplet
    neovim-unwrapped
    vlc
    hyprlock
    hyprcursor
    hyprpicker
    wlogout
    cloudflared
    discord
    vscode
    vesktop
    vencord
    spotify
    obs-studio
    (pkgs.wrapOBS {
      plugins = with pkgs.obs-studio-plugins; [
        obs-multi-rtmp
      ];
    })
    polkit_gnome
    prismlauncher
    heroic
    lutris
    peazip
    gimp3
    kdePackages.kdenlive
    google-chrome
    brave
    tor-browser
    kitty
    thunderbird-bin
    mcaselector
    btop
    zapzap
    libreoffice-fresh
    gnome-disk-utility
    p7zip
    unzip
    zip
    gcc
    clang
    cmake
    pkg-config
    gnumake
    python3
    nodejs
    mangohud
    gamescope
    vkbasalt
    goverlay
    protonup-qt
    qpwgraph
    helvum
    ffmpeg-full
    waybar-mpris
    grim
    slurp
    swappy
    grimblast
    playerctl
    nmap
    iperf3
    httrack
    tailscale
    bottles
    pavucontrol
    gh
    unrar
    ripgrep
    appimage-run
    sddm-astronaut
    kdePackages.qtsvg
    kdePackages.qtmultimedia
    kdePackages.qtvirtualkeyboard
    killall
    microfetch
    tldr
    nix-prefetch-scripts
    libjxl
    fzf
    fd
    jq
    lm_sensors
    virt-viewer # View Virtual Machines
    spice
    spice-gtk
    spice-protocol
    spice-vdagent
    win-virtio
    win-spice
    lazydocker
    docker-client
    lf
    hyprpolkitagent
    flatpak
    jetbrains.clion
    jetbrains.writerside
    jetbrains.webstorm
    jetbrains.rust-rover
    jetbrains.ruby-mine
    jetbrains.rider
    jetbrains.pycharm-community-bin
    jetbrains.phpstorm
    jetbrains.mps
    jetbrains.idea-community-bin
    jetbrains.goland
    jetbrains.gateway
    jetbrains.dataspell
    jetbrains.datagrip
    jetbrains.aqua
    jetbrains-mono
    jetbrains-toolbox
    ninja
    lld
    mold
    gdb
    lldb
    valgrind
    strace
    devbox
    direnv
    just
    shellcheck
    hadolint
    bat
    eza
    glow
    rustup
    go
    deno
    dotnet-sdk_8
    lua
    luajit
    meson
    python3Packages.pytest
    python3Packages.coverage
    cargo-audit
    cargo-outdated
    git-lfs
    pre-commit
    act
    nixfmt-rfc-style
    alejandra
    flatpak-builder
    rpm
    dpkg
    wireshark
    tshark
    mitmproxy
    openssl
    curlie
    httpie
    docker-compose
    zoxide
    atuin
    thefuck
    broot
    zulu
    zulu8
    zulu24
    zulu23
    zulu17
    zulu11
    ydotool
    libnotify
  ];
  programs.nh = {
    enable = true;
    clean = {
      enable = true;
      extraArgs = "--keep-since 7d --keep 3";
    };
    flake = "/etc/nixos#default";
  };
  programs.gnupg.agent = {
    enable = true;
    enableSSHSupport = true;
  };
  programs.dconf.enable = true;
  programs.zsh.enable = true;
  programs.virt-manager.enable = true;
}
